---
title: "Final Report"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(httr)
library(lubridate)
library(plotly)

```

&nbsp;

### Motivation
One of our group members' had the unfortunate experience of getting her car towed last year, due to parking near by a fire hydrant in Minnesota. A news report published by New York Post about locations drivers were most likely to get a parking ticket in NYC between October 2020 and September 2021 [-Link]( https://nypost.com/2021/11/18/these-are-the-worst-nyc-streets-for-getting-a-parking-ticket/). Thus, we were intrigued by the potential of investigating parking violations in NYC in 2021, with a particular interest in fire hydrant parking violations. 

&nbsp;

### Questions
1. When and where are parking violations in NYC most likely to be found? 
2. Which borough had the most violations? Which borough paid the most in fines?
3. What does the distribution of violations look like over other variables in the dataset borough, date, vehicle type)? 
4. Are the number of parking violations related to fire hydrants the same across the five boroughs? Can we find the hydrants that seem to be ticketed the most commonly?

&nbsp;

### Data Processing and Cleaning

We used two datasets from NYC OpenData to construct our main dataset for analysis and also utilized a few other datasets (both available online and scraped from the internet) to supplement our analysis

* Open Parking and Camera Violations 
[-Link](https://data.cityofnewyork.us/City-Government/Open-Parking-and-Camera-Violations/nc67-uf89)

The Open Parking and Camera Violations dataset hosted online contains data on 73.6 million parking violations from 2016 to 2021. We filtered the dataset on the website page to remove redundant information and downloaded the dataset after filtering, as it was too large to download outright. We stored the dataset in a Google Drive folder, as it exceeded the size limits for GitHub. We are interested in parking violation in five boroughs, Manhattan, Kings, The Bronx, State Island, and Queens. After importing the dataset into R and tidying the dataset, we were ultimately interested in the following variables:

* `summons_number`: unique violation identifier
* `borough`: borough violation was issued in
* `issue_date` (also split into `month`, `date`, `year`): date violation was issued on
* `weekday`: day of the week violation was issued
* `hour` and `min`: time violation was issued

* Parking Violations Issued - Fiscal Year 2021
[-Link](https://data.cityofnewyork.us/City-Government/Parking-Violations-Issued-Fiscal-Year-2021/kvfd-bves)

The Parking Violations Issued - Fiscal Year 2021 dataset provides information about the violations issued during the respective fiscal year. This dataset provides us with approximate locations where each parking violation was issued. In addition, this dataset also provides us with information about the car type. We mostly made use of the following variables in the dataset:

* `summons_number`: unique violation identifier, used to join dataset with the Open Parking dataset
* `geo_nyc_address`: combination of a few address components in the raw data, passed into NYCGeoSearch in mapping analysis
* `vehicle_body_type`: type of vehicle the violation was issued to
* `vehicle_year`: year of the vehicle


* Hydrants in NYC
[-Link](https://data.cityofnewyork.us/Environment/NYCDEP-Citywide-Hydrants/6pui-xhxz)

This dataset contains the locations of all fire hydrants in NYC. After tidying the dataset and recoding some columns, we are most interested in the following variables: 

* `borough`: borough the hydrant is located in
* `unitid`: unique hydrant identifier
* `lat` and `long`: latitude and longitude coordinates of the hydrant


### Exploratory Data Analyses

We performed a few initial analyses to better understand the trends parking violations in the city may follow. 

We first conducted a frequency analysis to investigate trends in counts of parking violations. 

Afterwards, we investigated the distribution of number of violation over a day and in each weekday and by vehicle types. Finally, we looked at the distribution of fine amounts by boroughs.

[Violation Frequency](frequencyI.html)

[Violation Timeline](timeline-part.html)

[Violation by Vehicle Type](vehicle.html)

[Fine Amount](fines.html)

&nbsp;

### Statistical Analyses

We conducted a number of statistical tests to test if the trends we observed were significant.

First, We performed a one-way ANOVA test across the weekdays and months parking violations occurred in to see if there is significant difference within the groups of time. 

Then, we performed a chi-squared test to test the homogeneity of violation types in five boroughs. 

Finally, we performed a proportion test to examine whether the proportion of fire hydrant violations (against the total population in each borough) differs across boroughs. 


#### Mapping and Spatial Analysis

Finally, we constructed a map of parking violations related to fire hydrants. we focused on the distribution of suspicious hydrants distribution that may cause the violation tickets. The basic layer represents the various borough in colors. The red points is the hydrants location which some cars had encountered the violation nearby.

&nbsp;

### Discussion

EDA Findings:

* **Brooklyn** has the highest number of tickets among five boroughs. Manhattan and Queens have approximately the same number of tickets. 

* There is a sharp increase in number of tickets in **October** in all boroughs. 

* Top three types of violation: **No Parking-Street Cleaning**, **Inspection Sticker Expired/Missing**, **Fail to Display a muni-meter receipt**.

* **Saturday** has the lowest violation counts and **Friday** had the second lowest counts comparing to all other weekdays.

* Violation increases from **6:00 AM** to **8:00 AM**, remains high in **8:00 AM** to **2:00 PM**, decrease from **2:00 PM** to **7:00 PM**.

* Average fine amount is **highest** in **Manhattan** and **lowest** in **Staten Island**. There is **significant difference** between fine amounts and at least 2 boroughs.

* **Suburban(SUBN)** is the vehicle type that has the highest number of violation.

Statistical Analysis Findings:

* **ANOVA test**: the parking violation counts are associated with **month** and **weekday**. 

* **Chi-square test**: the proportions of violation amounts is **different** among boroughs. 

* **Proportion test**: the proportions of people getting fire hydrant violations are **different** across boroughs. 

Spatial Analysis Findings:



