---
title: "frequencyI"
authors: Yuanyuan Zeng
output: html_document
---
```{r setup, include=FALSE}

library(tidyverse)
library(httr)
library(lubridate)
library(plotly)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

source("code/formatting.R")
```

A. Number

1）Frequency of tickets in five boroughs (Manhattan, Kings, The Bronx, State Island, Queens)
```{r}
violation1 = read_csv("./Open_Parking_and_Camera_Violations.csv") %>% 
  janitor::clean_names() %>%
  rename(borough = county) %>%  # rename county to borough
  mutate(
    borough = case_when(
      borough %in% c("BK","K", "Kings") ~ "Brooklyn",
      borough %in% c("BX", "Bronx") ~ "Bronx",
      borough %in% c("Q", "QN", "Qns") ~ "Queens",
      borough %in% c("ST", "R", "Rich", "RICH") ~ "State Island",
      borough %in% c("NY", "MN") ~ "Manhattan"),
      issue_date = as.Date(issue_date, format = "%m/%d/%y"),
      weekday = weekdays(issue_date),
      year = year(issue_date),
      month = month(issue_date),
      day = day(issue_date)
    )  %>%  # make the borough the same 
  filter(borough != "A",                  # get rid of "A"
         weekday != "NA",
         month != "11",
         month != "12")  # remove data that cannot turn into weekday

  
# another potential cleaning 1)select the variables we needed 2)convert the mon into character ?
violation1 %>% 
  count(borough) %>% 
  mutate(
    borough = fct_reorder(borough, n)) %>% 
  plot_ly(x = ~borough, y = ~n, color = ~borough, type = "bar", colors = "viridis") %>% 
  layout(title = "Frequency of Tickets in Boroughs in 2021",
         xaxis = list(title = "Borough"),
         yaxis = list(title = "Number of Tickets"))

violation1 %>% 
  group_by(borough) %>%
  count(month) %>% 
  mutate(month = month.abb[as.numeric(month)],
         month = fct_relevel(month, c("Jan", "Feb", "Mar", "Apr","May","Jun", "Jul", "Aug", "Sep", "Oct"))) %>% 
      plot_ly(x = ~month, y = ~n, color = ~borough, type = "bar", colors = "viridis")%>%
  layout(title = "Frequency of Tickets in Boroughs in 2021",
         xaxis = list(title = "Borough"),
         yaxis = list(title = "Number of Tickets in Each Month in 2021"))


```

