---
title: "Final project proposal"
date: "2021-11-13"
output: github_document
---
## Group members

* Yuanyuan Zeng (yz4181)
* Haotian Wu (hw2849)
* Dantong Zhu (dz2451)
* Yan Wang (yw3773)
* Waveley Qiu (wq2162)

## Tentative Project Title

NYC parking violations

## Motivation

As one of our group member's car was towed last year because of parking near by a fire hydrant in Minnesota, we come up with the idea about doing something related with parking violation.

Our project focuses on the NYC parking violations, we want to investigate the association between parking violation, location and penalty cost.

## Intended final product

In the end, we want to make a webpage for our project. The website will include all of our data analysis, statistical models and along with a final report. We will also make a video to explain the whole process of our project.

## Anticipated Data Sources

We found two data sets related to our topic from the NYC open data.

* Open Parking and Camera Violations

https://data.cityofnewyork.us/City-Government/Open-Parking-and-Camera-Violations/nc67-uf89

* Parking Violations Issued - Fiscal Year 2021

https://data.cityofnewyork.us/City-Government/Parking-Violations-Issued-Fiscal-Year-2022/pvqr-7yc4

## planned analyses / visualizations / coding challenges

## Planned timeline



