---
title: "Final project proposal"
date: "2021-11-13"
output: github_document
---
## Group Members

* Yuanyuan Zeng (yz4181)
* Haotian Wu (hw2849)
* Dantong Zhu (dz2451)
* Yan Wang (yw3773)
* Waveley Qiu (wq2162)

## Tentative Project Title: NYC Parking Violations

## Motivation

One of our group members' had the unfortunate experience of getting her car towed last year, due to parking near by a fire hydrant in Minnesota. As a result, when we discovered that NYC has made datasets cataloging individual parking violations available, we were intrigued by the potential of investigating this topic on a city-wide level. 

We are interested in seeing if any conclusions can be made about the frequency at which specific parking violations are given out and if there are any factors that may be associated to receiving one in 2021. 

## Intended Final Product

We intend to create a webpage for our project that will include all of our data analysis, statistical models, and our final report. We will also upload a screencast presentation that will explain the process behind our project.

## Anticipated Data Sources

We anticipate using three datasets from NYC OpenData in our project:

* Open Parking and Camera Violations

https://data.cityofnewyork.us/City-Government/Open-Parking-and-Camera-Violations/nc67-uf89

* Parking Violations Issued - Fiscal Year 2021

https://data.cityofnewyork.us/City-Government/Parking-Violations-Issued-Fiscal-Year-2021/kvfd-bves

* Parking Violations Issued - Fiscal Year 2022

https://data.cityofnewyork.us/City-Government/Parking-Violations-Issued-Fiscal-Year-2022/pvqr-7yc4

## Planned Analyses / Visualizations / Coding Challenges

We plan on conducting the following analyses:

* Frequency of each type of violation

* Total fine amount and average fine amount for type of violation

We plan on constructing the following visualizations:

* Histogram showing number of parking violation from each state in NYC

* Plot showing number of parking and camera violation over the day

* Map showing the location of violation and number of violation in each county

We expect the data cleaning portion of this project to be significantly challenging, as we are working with a rather large dataset (about 72 million observations). To help mitigate some of the difficulty of working with a larger dataset, we plan on restricting the scope of our analysis to just the fiscal years of 2021 and 2022 and possibly sampling from the resulting dataset if there is still need to.

Additionally, in our initial investigation of the datasets, we noticed that a significant number of observations had missing values for a number of variables. We will need to discuss as a group how to handle these situations.

## Planned Timeline

11/13/2021                  Proposal

11/13/2021-11/16/2021       Revise Proposal

11/16/2021-11/23/2021       Cleaning the data set, EDA

11/23/2021-11/28/2021       Narrow down analysis, start coding for report

11/29/2021-12/03/2021       Start on webpage & Video

12/04/2021-12/10/2021       Report (first draft), update programming as necessary

12/13/2021                  Finish report

12/15/2021                  Put everything together

12/16/2021                  Submission 



